baseURL: "https://blog.javivela.dev/"
title: "Javi Vela Blog"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
defaultContentLanguage: "es"
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  es:
    params:
      languageAltTitle: Español
      profileMode:
        imageHeight: 120
        imageTitle: "Javi Vela fotografía"
        imageUrl: "JavierVela.jpg"
        imageWidth: 120
        subtitle: > 
          <br/>
          Mi viaje profesional comenzó hace más de 20 años como desarrollador .NET, durante este tiempo he trabajado como desarrollador, arquitecto de soluciones y líder técnico en diversas empresas. He tenido la oportunidad de trabajar en proyectos internacionales, donde he adquirido experiencia en el desarrollo de aplicaciones y la implementación de arquitecturas escalables.
          <br/>
          <br/>
          En los últimos años, me he especializado en tecnologías cloud y metodologías Devops, lo que me ha permitido adquirir un profundo conocimiento en la creación de infraestructuras como código y la automatización de procesos.
          <br/>
          <br/>
          Este blog es mi manera de compartir el conocimiento adquirido a lo largo de estos años. Aquí encontrarás artículos sobre Devops, Azure, AWS, CI/CD, K8S, contenedores y arquitectura.
    languageName: "Español"
  
    weight: 2
    menu:
      main:
        - name: Posts
          url: posts/
          weight: 1
        - name: Buscar
          url: search/
          weight: 10
        - name: Archivos
          url: archives/
          weight: 10

  en:
    contentDir: content/en
    disabled: false
    languageCode: en
    languageName: English
    params:
      profileMode: 
        imageHeight: 120
        imageTitle: "Javi Vela photography"
        imageUrl: "JavierVela.jpg"
        imageWidth: 120
        subtitle: >
          <br/>
          My professional journey began more than 20 years ago as a .NET developer. During this time, I have worked as a developer, solutions architect, and technical leader in various companies. I've had the opportunity to work on international projects, where I've gained experience in application development and implementing scalable architectures. 
          <br/>
          <br/>
          In recent years, I have specialized in cloud technologies and DevOps methodologies, which has allowed me to acquire deep knowledge in creating infrastructure as code and process automation. 
          <br/>
          <br/>
          This blog is my way of sharing the knowledge acquired throughout these years. Here you will find articles about DevOps, Azure, AWS, CI/CD, K8S, containers, and architecture.
    weight: 2
    menu:
      main:
        - name: Posts
          url: en/posts/
          weight: 1
        - name: Buscar
          url: search/
          weight: 10
        - name: Archivos
          url: archives/
          weight: 10
pagination:
  pagerSize: 8

params:
  librecounter:
    enabled: true

  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  # description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  # author: Theme PaperMod
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: ["x", "linkedin"]
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  # comments: false
  images: ["papermod-cover.png"]

  profileMode:
    enabled: true
    title: Javi Vela Blog

    buttons:
      - name: Posts
        url: posts/

  # homeInfoParams:
  #   Title: Javi Vela Blog
  #   Content: "Soy arquitecto de soluciones y un apasionado de las tecnologías cloud y tecnologías microsoft. Este es mi sitio web para hablar sobre DevOps, Azure, AWS, CI/CD, K8S, contenedores y arquitectura."

  socialIcons:
    - name: github
      url: "https://github.com/fjvela"
    - name: x
      url: "https://x.com/jvela"
    - name: linkedin
      url: "https://www.linkedin.com/in/javiervelaaylon/"
    - name: RsS
      url: "index.xml"

  # editPost:
  #   URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # label:
  #   text: "Home"
  #   icon: icon.png
  #   iconHeight: 35

  analytics:
    google:
      SiteVerificationTag: Z9k5TW79n5H64zWLwEcNkbNITNDDepKoE2udZjirxXM
    bing:
      SiteVerificationTag: 6A293DF736526A40A24D911811A73F7D

  # assets:
  #   favicon: "<link / abs url>"
  #   favicon16x16: "<link / abs url>"
  #   favicon32x32: "<link / abs url>"
  #   apple_touch_icon: "<link / abs url>"
  #   safari_pinned_tab: "<link / abs url>"

  # cover:
  #   hidden: true # hide everywhere but not in structured data
  #   hiddenInList: true # hide on list pages and home
  #   hiddenInSingle: true # hide on single page

  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   keys: ["title", "permalink", "summary", "content"]

taxonomies:
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true
#   highlight:
#     # anchorLineNos: true
#     codeFences: true
#     guessSyntax: true
#     lineNos: true
#     # noClasses: false
#     style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  x:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
